name: si2mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  http: ^1.3.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  url_launcher: ^6.3.1
  speech_to_text: ^7.0.0
  path_provider: ^2.1.5
  vector_math: ^2.1.4
  flutter_archive: ^6.0.3
  flutter_chat_ui: ^2.5.2
  flutter_chat_core: ^2.6.1
  model_viewer_plus: ^1.9.3
  camera: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/