// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8nPwHVoyDTEu_5fyVni8Q_wL8OiTs0jo',
    appId: '1:1038377162874:web:135b81982a5124fb3383c3',
    messagingSenderId: '1038377162874',
    projectId: 'si2-p1-mobile',
    authDomain: 'si2-p1-mobile.firebaseapp.com',
    storageBucket: 'si2-p1-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrZTdYH7ZlY4n9GT7U_iTeGvxmeypBqHE',
    appId: '1:1038377162874:android:004b29b4cc40b9093383c3',
    messagingSenderId: '1038377162874',
    projectId: 'si2-p1-mobile',
    storageBucket: 'si2-p1-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvcYkPuGDlfxtFBV9MgFe76fS4d-wRQ0c',
    appId: '1:1038377162874:ios:dce03f043539df943383c3',
    messagingSenderId: '1038377162874',
    projectId: 'si2-p1-mobile',
    storageBucket: 'si2-p1-mobile.firebasestorage.app',
    iosBundleId: 'com.example.si2P1Mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvcYkPuGDlfxtFBV9MgFe76fS4d-wRQ0c',
    appId: '1:1038377162874:ios:dce03f043539df943383c3',
    messagingSenderId: '1038377162874',
    projectId: 'si2-p1-mobile',
    storageBucket: 'si2-p1-mobile.firebasestorage.app',
    iosBundleId: 'com.example.si2P1Mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8nPwHVoyDTEu_5fyVni8Q_wL8OiTs0jo',
    appId: '1:1038377162874:web:8654f59fbcc561af3383c3',
    messagingSenderId: '1038377162874',
    projectId: 'si2-p1-mobile',
    authDomain: 'si2-p1-mobile.firebaseapp.com',
    storageBucket: 'si2-p1-mobile.firebasestorage.app',
  );
}
